### PR TITLE
allow space after function keyword

### PR DESCRIPTION
**Pull request by alexanderjeurissen**
It's common at least for most of our projects (360 feedback, Conversations, Learning Spaces) to use a space after the function keyword as in:

```javascript
function () {

}

function name () {

}
```

This commit overwrites the airbnb rules that disallow this.

### CODE REVIEW

**Comment by alexanderjeurissen** [comment]
@ismay not sure if Capp-front uses spaces after `function` keyword, could you check this and let me know ?

**Comment by ismay** [comment]
We don't. But I don't really care which we choose, so with spaces is fine by me.

**Comment by ismay** [comment]
Would you mind modifying the eslint config as well so that it's consistent with these changes?

**Comment by alexanderjeurissen** [comment]
@ismay @tarzan ready to review, I incorporated the jscsrc changes to the eslint config. And changed the eslint config to json format so it's more in line with the other config files.

**Pull request merged**
